name: Run Python Script on .txt Commit

on:
  push:
    paths:
      - '**/*.txt'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Get modified .txt file
      id: get-file
      run: echo "::set-output name=file::$(git diff --name-only HEAD^ HEAD | grep '.txt$')"

    - name: Run Python script
      run: python your_script.py ${{ steps.get-file.outputs.file }}
